nvidia:
  compiler:
      - toolchain: gcc
        spec: gcc
      - toolchain: llvm
        spec: nvhpc
  unify: true
  mpi:
    spec: cray-mpich
    gpu: cuda
  specs:
  - cmake%gcc
  - libtree%gcc
  - python@3.10%gcc
  - cuda@12%gcc
  - diffutils%gcc
  - eccodes@2.25.0%nvhpc +tools +fortran +aec +openmp jp2k=jasper
  - hdf5%nvhpc +fortran
  - netcdf-c@4.8.1%gcc
  - netcdf-cxx4%gcc
  - netcdf-fortran@4.5.4%nvhpc
  - boost%gcc
  #- openmpi@4.1.6%nvhpc +cuda fabrics=ucx schedulers=auto
  #- ucx@1.14.1%gcc +rdmacm +cma +verbs +dm +optimizations +gdrcopy ~assertions ~debug
  # below are libraries that we explicitly force to use %gcc
  # papi with cuda, nvml and "software defined events"
  - papi%gcc +cuda +nvml +sde
  - autoconf%gcc
  - automake%gcc
  - ca-certificates-mozilla%gcc
  - gnuconfig%gcc
  - gmake%gcc
  - hwloc%gcc
  - jasper%gcc
  - libaec%gcc
  - libiconv%gcc
  - libjpeg-turbo%gcc
  - libxcrypt%gcc
  - libxml2%gcc
  - m4%gcc
  - numactl%gcc
  - osu-micro-benchmarks@5.9%nvhpc
  - nasm%gcc
  - ncurses%gcc
  - openssl%gcc
  - perl%gcc
  - zlib%gcc
  - xz%gcc
  variants:
  - cuda_arch=90
  - +mpi
  - +cuda
  packages:
  - curl
  - perl
  - pkgconf
  views:
    nvidia:
